### PR TITLE
CLI Command for fetching events as pages

### PR DESCRIPTION
**Pull request by karfau**
This is my PR for #26, at least this is what worked for me.

I think there is room for improvement on many levels, but first wanted to hear your opinion.

Besides adding the functionality, I moved some code from `facebook.php` to `classes/FacebookEvents.php` to reuse code in both `facebook.php` and the new `cli/FetchEventsCommand.php`.

Usage (after configuring page id and facebook credentials):
```bash
[php] bin/plugin facebook fetch-events [user/pages/events]
```

Best Christian

### CODE REVIEW

**Comment by mikahanninen** [comment]
I am reviewing your pull request and fixing some issues mainly due to the case that event does not necessarily have 'original_end' property. But seems good so far.

**Comment by mikahanninen** [comment]
Can you tell me what is the purpose of `date` and `unpublish_date` in the `facebook.event.page.md.twig` file ? Why they are just not `original_start` and `original_end` ?

**Comment by karfau** [comment]
Great, haven't thought about the case of `original_end` date not being set. (Isn't the parsing in the plugin setting it to the start date when it is not present?)

These fields are "special names" for pages in Grav:
- `date` is one way of [sorting page collections](https://learn.getgrav.org/content/collections#ordering-options)
- `unpublish_date` will [hide the page](https://learn.getgrav.org/content/headers#unpublish-date) after that time.

If you want anything added/ documented/ cleared up from my side just tell me!

**Comment by karfau** [comment]
Since facebook events are no longer working anyways (at least when I last checked, I'll close this PR

**Pull request closed without merging**
